version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - ${WEBSERVER_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./document_root:/var/www/html
    depends_on:
      - php
 
  php:
    build: ./php
    volumes:
      - ./document_root:/var/www/html
    depends_on:
      - db
 
  db:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mysql-data:

